{{- if ne ((.Values.serviceAccount).create) false }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flask-app.serviceAccountName" . }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
{{- end }}
